### ISSUE TITLE
How do I download my binary?

### ISSUE THREAD

**Issue by GirkovArpa** [NathanARoss/ncc#1]
I wrote:

```cpp
typedef long int i32;

i32 sum(i32 a, i32 b) {
    return a + b;
}
```

And clicked the play button but get this error in the console;

```javascript
CompileError: WebAssembly.instantiate(): invalid local type @+90
```

When I click the Wasm button it shows annotated Wasm but how do I download it?

**Comment by NathanARoss** [comment]
You are the first person to ever comment on one of my projects.  Thank you.

To directly answer your question, downloading the .wasm binary is accomplished by right-clicking the WebAssembly icon.  This is obviously not the ideal user experience, but I considered downloading the .wasm binary to be a debugging tool rather than a primary feature at the time.  If you're on mobile, long-tapping the WebAssembly icon should also work.  I'll implement a proper download button once I work on this project again.

About the error you mentioned:
At this point in the project, only basic int and float operations are supported.  I have not even implemented automatic casting from int to float, so mixing types won't work.  What I have done is take all the work I did for this project that was submitted in another repo and moved it here.  The primary issue was that I upgraded from Clang 9 to Clang 10 without testing.  I have resolved the issues and this build should work again.

I am currently handling the end of the semester assignments, so I do not expect to be available to implement many more features soon.  I did fix this project so the old demo works again.  Please delete all code from your editor window, press play to save, then refresh the browser window to restore the sample program.  This will indicate what I have implemented so far.

Thank you for reaching out to me.  I appreciate the interest in my project.

**Comment by NathanARoss** [comment]
I should also mention that I haven't implemented typedefs or pre-processor directives either.  There is only a very small subset of C++ I have implemented so far.  If I expect this project to go anywhere, I need to study C++ compilers and take another approach rather than trying to implement one language feature at a time.
